### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by abdennour** [stfsy/prometheus-what-active-users-exporter#32]
I would like to thank you for this awesome prometheuse exporter.
I am wondering if there is also a ready-made Grafana dashboard (json file) that can be provided along side.

**Comment by stfsy** [comment]
@abdennour thanks for the  feedback, that's always nice to hear 😀

There's no dashboard, at least that i'm aware of. 

For my private usage, I'm using a simple graph panel that triggers an alarm whenever `what_user_sessions_currently_active{instance=\"<ip and port of exporter here\"}` is greater than one

![image](https://user-images.githubusercontent.com/2894615/148096120-bf5a3eb3-7713-47db-a3ef-56089660270d.png)

**Comment by abdennour** [comment]
we are lazy guys 😄 , we want read-made stuff to be just reused
but that query is fair enough! Thank you!

**Comment by abdennour** [comment]
@stfsy  Or `sum(what_user_sessions_currently_active) by (service)` better

**Comment by zhouwp4** [comment]
> 

do you have this grafana json file?tks
