### ISSUE TITLE
Wrong Output being Produced

### ISSUE THREAD

**Issue by akeslo** [stfsy/prometheus-what-active-users-exporter#83]
Great idea and utility! This doesn't seem to reflect active session for me on _Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-56-generic x86_64)_.  It often just shows 0, sometimes I'll get a 1.  Any known issues here?

W output:
![image](https://user-images.githubusercontent.com/3003773/210471263-888bf660-ab34-4ffb-8259-70fe9fc039d8.png)

prometheus-what-active-users-exporter output:
![image](https://user-images.githubusercontent.com/3003773/210471306-4fde3460-d38a-4736-b214-0ad03c5accf1.png)

**Comment by stfsy** [comment]
@akeslo thanks for the feedback and thank you for getting in touch 👍 

I dont know of any issues and the ouput of `w` command on your screenshot looks fine. 

Did you start the exporter with retention or scrape interval flags?

**Comment by stfsy** [comment]
@akeslo you probably know what i am talking about: You implement things and a few months later you cannot remember why you did it that way. I think what you found was a deliberate choice to try and prevent duplication of metrics from a single host and user.

I implemented a simpler version now. `--metrics.retention` is not used anymore. `--scrape.interval` defines how often the `w` command will be executed. Until another `w` command was executed, metrics and sessions will be cached.

Let me know what you think :)

**Comment by akeslo** [comment]
t

> @akeslo you probably know what i am talking about: You implement things and a few months later you cannot remember why you did it that way. I think what you found was a deliberate choice to try and prevent duplication of metrics from a single host and user.
> 
> I implemented a simpler version now. `--metrics.retention` is not used anymore. `--scrape.interval` defines how often the `w` command will be executed. Until another `w` command was executed, metrics and sessions will be cached.
> 
> Let me know what you think :)

Absolutely, I do know what you are talking about :).  Thanks for this, works great!

**Comment by akeslo** [comment]
@stfsy the variables should eventually reduce back to 0 when no active sessions exist correct? I'm noticing now that the count never seems to go below 0 for _what_user_sessions_currently_active_ and _what_each_session_currently_active_

**Comment by stfsy** [comment]
@akeslo Yes! This sort of cleanup was handled by the retention policy before! And I did not test it yesterday. I added a test case now, patched it and released a new version.

Fingers crossed!

**Comment by akeslo** [comment]
@stfsy looks to be working as expected now, thanks for the update!
