### ISSUE TITLE
Hi，Do you have written rules?

### ISSUE THREAD

**Issue by 3721518** [stfsy/prometheus-what-active-users-exporter#86]
Do not know how to write the rules, please advise，thinks！

**Comment by 3721518** [comment]
@stfsy

**Comment by 3721518** [comment]
@stfsy    Hi, i want to find is the alert condition for this parameter.

**Comment by 3721518** [comment]
@stfsy Hi, i want to find is the alert condition for this parameter.

**Comment by 3721518** [comment]
@stfsy  Hi, i want to find is the alert condition for this parameter,thinks!   screenshot
![image](https://user-images.githubusercontent.com/68690637/212864448-baeddb80-c7f8-43d4-b2c8-8bbfe6eeefc0.png)
![image](https://user-images.githubusercontent.com/68690637/212864524-8d95bd11-2394-46d8-b19b-01c9eee2b381.png)

**Comment by 3721518** [comment]
@stfsy Simple example, is it possible？

**Comment by stfsy** [comment]
@3721518 you can check issue #32 there is an example for a Grafana dashboard. Unfortunately I do not have an example for alter Manager because i have never used it myself

**Comment by 3721518** [comment]
> @3721518 you can check issue #32 there is an example for a Grafana dashboard. Unfortunately I do not have an example for alter Manager because i have never used it myself

Thanks to for you，I've worked out this problem.

**Comment by 3721518** [comment]
@stfsy Now I have a very tricky problem, how to filter the specified IP？
